# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180725_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='jaeho', max_length=10),
            preserve_default=False,
        ),
    ]
